### ISSUE TITLE
Linux Mint 19 RazerBlackWidowElite Issues

### ISSUE THREAD

**Issue by BonitaTerror** [openrazer/openrazer#1053]
## Distribution
Linux Mint 19 Tara
### Support

- [Yes] Have you tried rebooting?
- [Yes] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

I am using polychromatic controller as a front end to modify my keyboard settings. Occasionally, it will work without a hitch, but quite frequently I will run into issues that polychromatic reports as likely a bug by the openrazer daemon. I thought I would just give some info here and see what others think.

When launching polychromatic I am greeted with the following error:

![image](https://user-images.githubusercontent.com/39413300/77240175-4b059400-6bb9-11ea-86b8-fbf9b0e6e3da.png)

I'm sure there are other logs to look into for info, but from all I can find there seem to be no other error reports

Finally the output (and exception traceback) from `openrazer-daemon -Fv` will likely be useful:

```
2020-03-21 21:27:01 | razer                          | INFO     | Found device.0: 0003:1532:0228.0003
2020-03-21 21:27:01 | razer.device0                  | INFO     | Initialising device.0 RazerBlackWidowElite
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/daemonize.py", line 245, in start
    self.action(*privileged_action_result)
  File "/usr/bin/openrazer-daemon", line 125, in run_daemon
    test_dir=args.test_dir)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 106, in __init__
    self._load_devices(first_run=True)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 400, in _load_devices
    razer_device = device_class(sys_path, device_number, self._config, testing=self._test_dir is not None, additional_interfaces=sorted(additional_interfaces))
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/keyboards.py", line 54, in __init__
    super(_RippleKeyboard, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/keyboards.py", line 23, in __init__
    super(_MacroKeyboard, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 482, in __init__
    super().__init__(device_path, device_number, config, testing, additional_interfaces, additional_methods)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 445, in __init__
    super().__init__(device_path, device_number, config, testing, additional_interfaces, additional_methods)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 88, in __init__
    DBusService.__init__(self, self.BUS_PATH, object_path)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/service.py", line 87, in __init__
    super(DBusService, self).__init__(bus_object, object_path)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 455, in __init__
    validate_object_path(object_path)
ValueError: Invalid object path '/org/razer/device/': contains invalid character ''

Stopping daemon.
Exception ignored in: <bound method RazerDevice.__del__ of RazerBlackWidowElite:>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 431, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 345, in close
    self._close()
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/keyboards.py", line 59, in _close
    super(_RippleKeyboard, self)._close()
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/keyboards.py", line 43, in _close
    self.key_manager.close()
AttributeError: 'RazerBlackWidowElite' object has no attribute 'key_manager'
```

I am appreciative of any help you may be able to offer!

**Comment by z3ntu** [comment]
Can you please run `hexdump -C /sys/bus/hid/drivers/razerkbd/0*/device_serial` ? It looks like you have another device where Razer failed to program the serial number correctly. Weirdly the existing code to handle these cases didn't seem to trigger for you.

**Comment by BonitaTerror** [comment]
Sure!

Here is the output:
```
alexander@totoro:~$ hexdump -C /sys/bus/hid/drivers/razerkbd/0003\:1532\:0228.0003/device_serial 
00000000  49 4f 31 39 34 30 46 32  36 35 30 30 30 31 39 0a  |IO1940F26500019.|
00000010
```

I shouldn't fail to mention that this output is from a time when polychromatic wasn't finding any issue connecting to the daemon. Perhaps if it stops working again, I can post the contents of that file again

**Comment by z3ntu** [comment]
So you mean it does work now?

**Comment by BonitaTerror** [comment]
It seems to randomly work and break. Would it be absurd to assume this could be a hardware issue?

**Comment by z3ntu** [comment]
Do you see many messages containing `razerkbd` in the dmesg?

**Comment by BonitaTerror** [comment]
A few, but only 1 really seems like it could be problematic

```
alexander@totoro:~$ dmesg | grep razerkbd
[    2.292262] razerkbd: loading out-of-tree module taints kernel.
[    2.292283] razerkbd: module verification failed: signature and/or required key missing - tainting kernel
[    2.720213] razerkbd 0003:1532:0228.0001: input,hidraw0: USB HID v1.11 Keyboard [Razer Razer BlackWidow Elite] on usb-0000:00:14.0-2/input0
[    2.780191] razerkbd 0003:1532:0228.0002: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer BlackWidow Elite] on usb-0000:00:14.0-2/input1
[    2.840216] razerkbd 0003:1532:0228.0003: input,hidraw2: USB HID v1.11 Mouse [Razer Razer BlackWidow Elite] on usb-0000:00:14.0-2/input2
```
