### ISSUE TITLE
Razer BlackWidow Elite - Brightness not working

### ISSUE THREAD

**Issue by Severus157** [openrazer/openrazer#1092]
### Distribution

OS: Arch Linux x86_64 
Host: AX370-Gaming 3 
Kernel: 5.6.3-arch1-1 
Packages: 1361 (pacman) 
Shell: bash 5.0.16 
Resolution: 3440x1440 
DE: Plasma 
WM: KWin 
Terminal: konsole 
CPU: AMD Ryzen 5 2600 (12) @ 3.163GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
Memory: 1972MiB / 32125MiB

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Hi,
I've got a bit of a problem with the Backgroundlighting of my BlackWidow Elite Keyboard. I have updated the System to a newer Kernel and now the Brightness is set to 0 from RazerGenie and I cannot change it.
The Keyboard itself seems fine, since the lighting works on a different PC not running Linux.

I've tried to add my user to plugdev group like some solutions proposed, but it didn't change anything.
The error I receive after starting up RazerGenie the second time is:

```
● openrazer-daemon.service - Daemon to manage razer devices in userspace
     Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-04-10 16:36:46 CEST; 1min 43s ago
       Docs: man:openrazer-daemon(8)
   Main PID: 857 (openrazer-daemo)
     CGroup: /user.slice/user-1000.slice/user@1000.service/openrazer-daemon.service
             └─857 openrazer-daemon

Apr 10 16:38:15 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:15 | razer.device0                  | DEBUG    | DBus call set_brightness
Apr 10 16:38:20 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:20 | razer.device0                  | DEBUG    | Sending observer message: ('effect', RazerBlackWidowElite:IO1839F31107680, 'setBrightness', 178)
Apr 10 16:38:20 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:20 | razer.device1                  | DEBUG    | Got observer message: ('effect', RazerBlackWidowElite:IO1839F31107680, 'setBrightness', 178)
Apr 10 16:38:20 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:20 | razer.device0                  | DEBUG    | DBus call set_brightness
Apr 10 16:38:25 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:25 | razer.device0                  | DEBUG    | Sending observer message: ('effect', RazerBlackWidowElite:IO1839F31107680, 'setBrightness', 204)
Apr 10 16:38:25 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:25 | razer.device1                  | DEBUG    | Got observer message: ('effect', RazerBlackWidowElite:IO1839F31107680, 'setBrightness', 204)
Apr 10 16:38:25 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:25 | razer.device0                  | DEBUG    | DBus call set_brightness
Apr 10 16:38:30 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:30 | razer.device0                  | DEBUG    | Sending observer message: ('effect', RazerBlackWidowElite:IO1839F31107680, 'setBrightness', 229)
Apr 10 16:38:30 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:30 | razer.device1                  | DEBUG    | Got observer message: ('effect', RazerBlackWidowElite:IO1839F31107680, 'setBrightness', 229)
Apr 10 16:38:30 antergos-pc openrazer-daemon[857]: 2020-04-10 16:38:30 | razer.device0                  | DEBUG    | DBus call set_brightness

```
Starting up on LTS Kernel 5.4.31-1-lts causes the same crashing of RazerGenie, but Lighting starts to work though. So it might be an issue caused by the New Kernel starting with OpenRazer?

**Comment by z3ntu** [comment]
Can you check that the effect isn't set to "Off" (or "None"), because if that effect is active, the brightness won't matter.

**Comment by Severus157** [comment]
Hi z3ntu,
The brightness is always recognised as off, even if it is on. Tried with Polychromatic as well as Razergenie.
Also the brightness is completly uncontrollable. It seems like it cannot be recognised, which setting is true.

Also it looks like the SerialNr cannot be recognised as well.
![image](https://user-images.githubusercontent.com/9520379/80305400-acbeac80-87bc-11ea-95c0-370bed5709a6.png)

lsusb gives out pretty strange things for the Razer Devices on the new Kernels. Problem persists on 5.6.6.
```
[s@antergos-pc ~]$ sudo lsusb -v | grep "1532"
can't get debug descriptor: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Bus 003 Device 005: ID 1532:005c Razer USA, Ltd 802.11n WLAN Adapter
  idVendor           0x1532 Razer USA, Ltd
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Bus 003 Device 004: ID 1532:0228 Razer USA, Ltd 
  idVendor           0x1532 Razer USA, Ltd
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
cannot read device status, Resource temporarily unavailable (11)
can't get debug descriptor: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
```
If I can get you any other outputs let me know.

**Comment by Severus157** [comment]
Still the same problem. Brightness completly crashes after sleep mode also. And before cannot be set anyways.

Solution steps I tried together with the new Kernel Update. Of completly removing openrazer and reinstall. Still nothing.
Have tried Polychromatic instead of RazerGenie. Error there: Daemon not Responding
`org.freedesktop.DBus.Error.ServiceUnknown: The name :1.114 was not provided by any .service files`

Starting up the driver manual brings up following error:

```
2020-05-20 21:43:17 | razer.device0                  | INFO     | Initialising device.0 RazerBlackWidowElite
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/daemonize.py", line 248, in start
    self.action(*privileged_action_result)
  File "/usr/bin/openrazer-daemon", line 121, in run_daemon
    daemon = RazerDaemon(verbose=args.verbose,
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/daemon.py", line 107, in __init__
    self._load_devices(first_run=True)
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/daemon.py", line 401, in _load_devices
    razer_device = device_class(sys_path, device_number, self._config, testing=self._test_dir is not None, additional_interfaces=sorted(additional_interfaces))
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/keyboards.py", line 54, in __init__
    super(_RippleKeyboard, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/keyboards.py", line 23, in __init__
    super(_MacroKeyboard, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/device_base.py", line 482, in __init__
    super().__init__(device_path, device_number, config, testing, additional_interfaces, additional_methods)
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/device_base.py", line 445, in __init__
    super().__init__(device_path, device_number, config, testing, additional_interfaces, additional_methods)
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/device_base.py", line 88, in __init__
    DBusService.__init__(self, self.BUS_PATH, object_path)
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/dbus_services/service.py", line 87, in __init__
    super(DBusService, self).__init__(bus_object, object_path)
  File "/usr/lib/python3.8/site-packages/dbus/service.py", line 459, in __init__
    validate_object_path(object_path)
ValueError: Invalid object path '/org/razer/device/': contains invalid character ''

Stopping daemon.
Exception ignored in: <function RazerDevice.__del__ at 0x7f0955134d30>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/device_base.py", line 431, in __del__
    self.close()
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/device_base.py", line 345, in close
    self._close()
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/keyboards.py", line 59, in _close
    super(_RippleKeyboard, self)._close()
  File "/usr/lib/python3.8/site-packages/openrazer_daemon/hardware/keyboards.py", line 43, in _close
    self.key_manager.close()
AttributeError: 'RazerBlackWidowElite' object has no attribute 'key_manager'
```
