### ISSUE TITLE
Daemon ValueError: Invalid Literal for int () with base 10: '\x02'

### ISSUE THREAD

**Issue by chadwl** [openrazer/openrazer#1354]
When trying to run polychromatic I recieve an error stating the 'Daemon not responding' followed by 'Poly-chromatic could not initialise the daemon. This could be caused by a bug with the daemon process. Exception: org.freedsetkop.DBus.Error.ServiceUnknown: The name :1.381 was not provided by any .service files' 

I then when into the console and ran the daemon in verbose mode to see the output of it and it presented me with the following information.

```Starting daemon.
2020-11-28 06:15:52 | razer                          | INFO     | Initialising Daemon (v2.9.0). Pid: 29522
2020-11-28 06:15:52 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus1800 ------------------------ (1532:0020)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus2000 ------------------------ (1532:005E)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusEliteDVaEdition ------------- (1532:006A)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusEssential ------------------- (1532:006B)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusV2 -------------------------- (1532:005B)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerAtherisReceiver -------------------- (1532:0062)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBaseStationChroma ------------------ (1532:0F08)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBasilisk --------------------------- (1532:0064)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBasiliskXHyperSpeed ---------------- (1532:0083)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2019 --------------------- (1532:0241)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowElite -------------------- (1532:0228)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowEssential ---------------- (1532:0237)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowLite --------------------- (1532:0235)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowStealth ------------------ (1532:011B)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowStealthEdition ----------- (1532:010E)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2012 ------------- (1532:010D)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2013 ------------- (1532:011A)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2016 ------------- (1532:0214)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXTournamentEditionChroma - (1532:021A)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlade15Advanced2020 ---------------- (1532:0253)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlade2018 -------------------------- (1532:0233)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlade2018Base ---------------------- (1532:023B)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlade2018Mercury ------------------- (1532:0240)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlade2019Adv ----------------------- (1532:023A)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlade2019Base ---------------------- (1532:0246)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBlade2019StudioEdition ------------- (1532:024D)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeEarly2020Base ----------------- (1532:0255)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeMid2019Mercury ---------------- (1532:0245)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017 ----------------------- (1532:0225)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017FullHD ----------------- (1532:022F)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2019 ----------------------- (1532:0234)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2019 ------------------- (1532:024C)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth2019 ------------------- (1532:0239)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthEarly2020 -------------- (1532:0252)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2017 --------------- (1532:0232)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2019 --------------- (1532:024A)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthMid2017 ---------------- (1532:022D)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerChromaHDK -------------------------- (1532:0F09)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerCynosaChroma ----------------------- (1532:022A)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerCynosaLite ------------------------- (1532:023F)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerCynosaV2 --------------------------- (1532:025E)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdder1800 --------------------- (1532:0038)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdder2000 --------------------- (1532:004F)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdder2013 --------------------- (1532:0037)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdder3500 --------------------- (1532:0054)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdder3_5G --------------------- (1532:0016)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderChroma ------------------- (1532:0043)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderElite -------------------- (1532:005C)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderEssential ---------------- (1532:006E)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderEssentialWhiteEdition ---- (1532:0071)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderV2 ----------------------- (1532:0084)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerExpert ----------------- (1532:0202)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerFirefly ---------------------------- (1532:0C00)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerFireflyHyperflux ------------------- (1532:0068)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerGoliathus -------------------------- (1532:0C01)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerGoliathusExtended ------------------ (1532:0C02)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerHuntsman --------------------------- (1532:0227)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerHuntsmanElite ---------------------- (1532:0226)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerHuntsmanTournamentEdition ---------- (1532:0243)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerImperator -------------------------- (1532:002F)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerKraken71 --------------------------- (1532:0501)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerKraken71Alternate ------------------ (1532:0506)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerKraken71Chroma --------------------- (1532:0504)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerKraken71V2 ------------------------- (1532:0510)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerKrakenKittyEdition ----------------- (1532:0F19)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerKrakenUltimate --------------------- (1532:0527)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerLanceheadTE ------------------------ (1532:0060)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerLanceheadWired --------------------- (1532:0059)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerLanceheadWireless ------------------ (1532:005A)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerLanceheadWirelessReceiver ---------- (1532:006F)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerLanceheadWirelessWired ------------- (1532:0070)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerMambaElite ------------------------- (1532:006C)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerMambaTE ---------------------------- (1532:0046)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerMambaWirelessReceiver -------------- (1532:0072)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerMambaWirelessWired ----------------- (1532:0073)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNaga2012 --------------------------- (1532:002E)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNagaChroma ------------------------- (1532:0053)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNagaTrinity ------------------------ (1532:0067)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNommoChroma ------------------------ (1532:0517)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNommoPro --------------------------- (1532:0518)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerTartarusV2 ------------------------- (1532:022B)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerViper ------------------------------ (1532:0078)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerViperMini -------------------------- (1532:008A)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerViperUltimateWired ----------------- (1532:007A)
2020-11-28 06:15:52 | razer                          | DEBUG    | Loaded device specification: RazerViperUltimateWireless -------------- (1532:007B)
2020-11-28 06:15:52 | razer                          | INFO     | Found device.0: 0003:1532:0084.0004
2020-11-28 06:15:52 | razer.device0                  | INFO     | Initialising device.0 RazerDeathAdderV2
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.restoreLastEffect method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceImage method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoEffectColors method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoEffect method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoEffectSpeed method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoWaveDir method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollEffectColors method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollEffectSpeed method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollEffect method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollWaveDir method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.dpi.maxDPI method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.dpi.getDPI method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.dpi.setDPI method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.getPollRate method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.misc.setPollRate method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoBrightness method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoBrightness method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollBrightness method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollBrightness method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoStatic method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoSpectrum method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoNone method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoReactive method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoBreathRandom method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoBreathSingle method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoBreathDual method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollStatic method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollSpectrum method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollNone method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollReactive method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollBreathRandom method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollBreathSingle method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollBreathDual method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setCustom method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setKeyRow method to DBus
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | DBus call set_dpi_xy
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | DBus call set_poll_rate
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | DBus call set_logo_brightness
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Sending observer message: ('effect', RazerDeathAdderV2:PM2003H14410409, 'setBrightness', 0)
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | DBus call set_scroll_brightness
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Sending observer message: ('effect', RazerDeathAdderV2:PM2003H14410409, 'setBrightness', 0)
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | DBus call set_static_effect
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Sending observer message: ('effect', RazerDeathAdderV2:PM2003H14410409, 'setStatic', 128, 0, 128)
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | DBus call set_static_effect
2020-11-28 06:15:52 | razer.device0                  | DEBUG    | Sending observer message: ('effect', RazerDeathAdderV2:PM2003H14410409, 'setStatic', 128, 0, 128)
2020-11-28 06:15:52 | razer                          | INFO     | Found device.1: 0003:1532:0228.0003
2020-11-28 06:15:52 | razer.device1                  | INFO     | Initialising device.1 RazerBlackWidowElite
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceImage method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.restoreLastEffect method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.getEffect method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.getEffectSpeed method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.getEffectColors method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.getWaveDir method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getKeyboardLayout method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.brightness.getBrightness method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.brightness.setBrightness method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setWave method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setStatic method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setSpectrum method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setReactive method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setNone method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathRandom method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathSingle method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathDual method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setCustom method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setKeyRow method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.led.gamemode.getGameMode method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.led.gamemode.setGameMode method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.led.macromode.getMacroMode method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.led.macromode.setMacroMode method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.led.macromode.getMacroEffect method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.led.macromode.setMacroEffect method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.macro.getMacros method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.macro.deleteMacro method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.macro.addMacro method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setStarlightRandom method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setStarlightSingle method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.chroma.setStarlightDual method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.custom.setRipple method to DBus
2020-11-28 06:15:52 | razer.device1                  | DEBUG    | Adding razer.device.lighting.custom.setRippleRandomColour method to DBus
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/daemonize.py", line 245, in start
    self.action(*privileged_action_result)
  File "/usr/bin/openrazer-daemon", line 140, in run_daemon
    daemon = RazerDaemon(verbose=args.verbose,
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 120, in __init__
    self._load_devices(first_run=True)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 482, in _load_devices
    razer_device = device_class(sys_path, device_number, self._config, self._persistence, testing=self._test_dir is not None, additional_interfaces=sorted(additional_interfaces))
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/keyboards.py", line 54, in __init__
    super(_RippleKeyboard, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/keyboards.py", line 23, in __init__
    super(_MacroKeyboard, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 1013, in __init__
    super().__init__(device_path, device_number, config, persistence, testing, additional_interfaces, additional_methods)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 976, in __init__
    super().__init__(device_path, device_number, config, persistence, testing, additional_interfaces, additional_methods)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 271, in __init__
    self.zone[i]["speed"] = int(self.persistence[self.storage_name][i + '_speed'])
ValueError: invalid literal for int() with base 10: '\x02'

Stopping daemon.
```

I've tried re-installing and whatnot however it's provided no resolve. The strange thing is it did work (polychromatic) at one point. It appears since a possible update this issue has been present. 

Is anybody able to provide some insight. It would be most helpful and welcomed. Thankyou in advance.

**Comment by brett-smith** [comment]
This looks the same as the issue I raised - https://github.com/openrazer/openrazer/issues/1351. 

You can get the daemon starting again by editing `.config/openrazer/persistence.conf` and finding the line that might look something like `backlight_speed = \x02` and changing that to a proper number, e.g.  `backlight_speed = 1`

**Comment by lah7** [comment]
Fixed! The daemon was been writing _bad_ data to `persistence.conf` for the starlight effect and some brightnesses, which caused the daemon to crash on its next launch.

You could [patch it using this commit](https://github.com/openrazer/openrazer/commit/604f1cab3a899a1877e787e0e6e42b58c289f3ed.patch) or install the `-git` or daily packages (if on Ubuntu) for the fix.

**Comment by chadwl** [comment]
Thank you all for your feedback. Issue is resolved.
