### ISSUE TITLE
Can not run or configure anything, orbweaver is not detected

### ISSUE THREAD

**Issue by vitacell** [openrazer/openrazer#168]
Arch gnulinux:
Linux Maquinon64 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

Running MATE with gtk3

+razer orbveawer and deathadder chroma

[vita@Maquinon64 ~]$ lsusb | grep '1532:'
Bus 002 Device 004: ID 1532:0043 Razer USA, Ltd 
Bus 001 Device 004: ID 1532:0113 Razer USA, Ltd RZ07-0074 Gaming Keypad [Orbweaver]

The razer-service is always running, already tryed everything. "razercfg" and "razerd" always worked fine for configure DA 3g and  DA Chroma. I uninstalled them, but now I am in trouble with all that razer-driver stuff. I can run razerCommander, only DA chroma is detected, and I can see only light value, nothing more, when I apply setting (even nothing is changed), in devices it adds another DA chroma after every apply.

[root@Maquinon64 vita]# pacman -Q | grep 'notify'
libnotify 0.7.7-1
notify-sharp 0.4.1-2
python-notify2 0.3-2
[root@Maquinon64 vita]# dbus-lauch /usr/bin/razercommander
bash: dbus-lauch: no se encontró la orden
[root@Maquinon64 vita]# dbus-launch /usr/bin/razercommander
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.razer': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/razer/client/__init__.py", line 20, in __init__
    self._dbus = session_bus.get_object("org.razer", "/org/razer")
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.razer was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 7, in <module>
    import device
  File "/usr/share/razercommander/device.py", line 10, in <module>
    device_manager = rclient.DeviceManager()
  File "/usr/lib/python3.6/site-packages/razer/client/__init__.py", line 22, in __init__
    raise DaemonNotFound("Could not connect to daemon")
razer.client.DaemonNotFound: Could not connect to daemon
[root@Maquinon64 vita]# razercommander
Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 7, in <module>
    import device
  File "/usr/share/razercommander/device.py", line 10, in <module>
    device_manager = rclient.DeviceManager()
  File "/usr/lib/python3.6/site-packages/razer/client/__init__.py", line 18, in __init__
    session_bus = _dbus.SessionBus()
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[root@Maquinon64 vita]# pacman -Q | grep 'razer'
python-razer 1.1.6-2
razer-daemon 1.1.6-3
razer-driver-dkms 1.1.6-1
razercommander-git 1.0.3-10

[vita@Maquinon64 ~]$ /usr/sbin/razer-service --foreground --verbose --run-dir ~/.razer-service/data --log-dir ~/.razer-service/logs --pid-file ~/.razer-service/daemon.pid
Daemon already exists. Please stop that one.
[vita@Maquinon64 ~]$ pkill razer-daemon
[vita@Maquinon64 ~]$ /usr/sbin/razer-service --foreground --verbose --run-dir ~/.razer-service/data --log-dir ~/.razer-service/logs --pid-file ~/.razer-service/daemon.pid
Daemon already exists. Please stop that one.
[vita@Maquinon64 ~]$ /usr/sbin/razer-service --foreground --verbose --run-dir ~/.razer-service/data --log-dir ~/.razer-service/logs --pid-file ~/.razer-service/daemon.pid
2017-01-24 04:20:45 | razer                          | INFO     | Initialising Daemon (v1.1.6). Pid: 975
2017-01-24 04:20:45 | razer.screensaver              | INFO     | Initialising DBus Screensaver Thread
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2012 --------------------- (1532:010D)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2013 --------------------- (1532:011A)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2016 --------------------- (1532:0214)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassic ------------------ (1532:011B)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChromaTournamentEdition - (1532:021A)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerDeathadderChroma ------------------- (1532:0043)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerDeathadderElite -------------------- (1532:005C)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerFireFly ---------------------------- (1532:0C00)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerImperiator ------------------------- (1532:002F)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaTE ---------------------- (1532:0046)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2017-01-24 04:20:45 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0208)
2017-01-24 04:20:45 | razer                          | INFO     | Found device.0: 0003:1532:0043.0005
2017-01-24 04:20:45 | razer.device0                  | INFO     | Initialising device.0 RazerDeathadderChroma
Traceback (most recent call last):
  File "/usr/sbin/razer-service", line 71, in <module>
    run()
  File "/usr/sbin/razer-service", line 65, in run
    daemonize(**daemon_args)
  File "/usr/lib/python3.6/site-packages/razer_daemon/daemon.py", line 113, in daemonize
    daemon = RazerDaemon(verbose, log_dir, console_log, run_dir, config_file, test_dir=test_dir)
  File "/usr/lib/python3.6/site-packages/razer_daemon/daemon.py", line 218, in __init__
    self._load_devices(first_run=True)
  File "/usr/lib/python3.6/site-packages/razer_daemon/daemon.py", line 422, in _load_devices
    razer_device = device_class(sys_path, device_number, self._config, testing=self._test_dir is not None)
  File "/usr/lib/python3.6/site-packages/razer_daemon/hardware/mouse.py", line 242, in __init__
    super(RazerDeathadderChroma, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/razer_daemon/hardware/device_base.py", line 79, in __init__
    DBusService.__init__(self, self.BUS_PATH, object_path)
  File "/usr/lib/python3.6/site-packages/razer_daemon/dbus_services/service.py", line 85, in __init__
    super(DBusService, self).__init__(bus_object, object_path)
  File "/usr/lib/python3.6/site-packages/dbus/service.py", line 455, in __init__
    validate_object_path(object_path)
ValueError: Invalid object path '/org/razer/device/': ends with '/' and is not just '/'
2017-01-24 04:20:47 | razer.screensaver              | INFO     | Initialising DBus screensaver object
2017-01-24 04:32:34 | razer.screensaver              | INFO     | Suspend screensaver
2017-01-24 04:32:34 | razer.screensaver              | INFO     | Resume screensaver

[vita@Maquinon64 ~]$ /usr/bin/razer-service --foreground --verbose --run-dir ~/.razer-service/data --log-dir ~/.razer-service/logs --pid-file ~/.razer-service/daemon.pid
2017-01-24 05:19:22 | razer                          | INFO     | Initialising Daemon (v1.1.6). Pid: 1586
2017-01-24 05:19:22 | razer.screensaver              | INFO     | Initialising DBus Screensaver Thread
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2012 --------------------- (1532:010D)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2013 --------------------- (1532:011A)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidow2016 --------------------- (1532:0214)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassic ------------------ (1532:011B)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChromaTournamentEdition - (1532:021A)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerDeathadderChroma ------------------- (1532:0043)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerDeathadderElite -------------------- (1532:005C)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerFireFly ---------------------------- (1532:0C00)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerImperiator ------------------------- (1532:002F)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaTE ---------------------- (1532:0046)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2017-01-24 05:19:22 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0208)
2017-01-24 05:19:22 | razer                          | INFO     | Found device.0: 0003:1532:0043.0005
2017-01-24 05:19:22 | razer.device0                  | INFO     | Initialising device.0 RazerDeathadderChroma
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding getSerial method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.version method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoActive method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoActive method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoEffect method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.getLogoBrightness method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoBrightness method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoStatic method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoPulsate method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoBlinking method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.logo.setLogoSpectrum method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollActive method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollActive method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollEffect method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollBrightness method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollBrightness method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollStatic method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollPulsate method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollBlinking method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollSpectrum method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.dpi.getDPI method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.dpi.setDPI method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.getPollRate method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Adding razer.device.misc.setPollRate method to DBus
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | DBus call set_logo_brightness
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Sending observer message: ('effect', RazerDeathadderChroma:PM1512121719163, 'setBrightness', 255)
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | DBus call set_scroll_brightness
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | Sending observer message: ('effect', RazerDeathadderChroma:PM1512121719163, 'setBrightness', 255)
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | DBus call set_logo_active
2017-01-24 05:19:22 | razer.device0                  | DEBUG    | DBus call set_scroll_active
2017-01-24 05:19:22 | razer                          | INFO     | Adding razer.devices.getDevices method to DBus
2017-01-24 05:19:22 | razer                          | INFO     | Adding razer.devices.enableTurnOffOnScreensaver method to DBus
2017-01-24 05:19:22 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
2017-01-24 05:19:22 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
2017-01-24 05:19:22 | razer                          | INFO     | Adding razer.devices.syncEffects method to DBus
2017-01-24 05:19:22 | razer                          | INFO     | Adding razer.daemon.version method to DBus
2017-01-24 05:19:22 | razer                          | INFO     | Adding razer.daemon.stop method to DBus
2017-01-24 05:19:22 | razer                          | INFO     | Serving DBus
2017-01-24 05:19:24 | razer.screensaver              | INFO     | Initialising DBus screensaver object
2017-01-24 05:19:31 | razer                          | DEBUG    | DBus called get_serial_list
2017-01-24 05:19:31 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-01-24 05:19:31 | razer.device0                  | DEBUG    | DBus call get_device_name
2017-01-24 05:19:31 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-01-24 05:19:31 | razer.device0                  | DEBUG    | DBus call get_firmware
2017-01-24 05:19:31 | razer.device0                  | DEBUG    | DBus call version
2017-01-24 05:19:31 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-01-24 05:19:31 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-01-24 05:20:31 | razer                          | DEBUG    | DBus called get_serial_list
2017-01-24 05:20:31 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-01-24 05:20:31 | razer.device0                  | DEBUG    | DBus call get_device_name
2017-01-24 05:20:31 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-01-24 05:20:31 | razer.device0                  | DEBUG    | DBus call get_firmware
2017-01-24 05:20:31 | razer.device0                  | DEBUG    | DBus call version
2017-01-24 05:20:31 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-01-24 05:20:31 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-01-24 05:21:38 | razer                          | DEBUG    | DBus called get_serial_list
2017-01-24 05:21:38 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-01-24 05:21:38 | razer.device0                  | DEBUG    | DBus call get_device_name
2017-01-24 05:21:38 | razer.device0                  | DEBUG    | DBus call get_device_type
2017-01-24 05:21:38 | razer.device0                  | DEBUG    | DBus call get_firmware
2017-01-24 05:21:38 | razer.device0                  | DEBUG    | DBus call version
2017-01-24 05:21:38 | razer.device0                  | DEBUG    | DBus call has_matrix
2017-01-24 05:21:38 | razer.device0                  | DEBUG    | DBus call has_matrix

[vita@Maquinon64 ~]$ polychromatic-controller
 ** Preference 'brightness' in 'PM1512121719163' non-existent. Using default 'None' instead.
 ** Preference 'effect' in 'PM1512121719163' non-existent. Using default 'None' instead.
 ** Preference 'effect' in 'PM1512121719163' non-existent. Using default 'None' instead.
 ** Preference 'effect' in 'PM1512121719163' non-existent. Using default 'None' instead.
 ** Preference 'effect' in 'PM1512121719163' non-existent. Using default 'None' instead.
Failed to toggle logo for Razer DeathAdder Chroma.
Exception: can't set attribute

[vita@Maquinon64 ~]$ /usr/bin/razercommander
WARNING:root:Brightness is not available
Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 527, in on_universalApplyButton_clicked
    currentFX = fxListBox.get_selected_row().value
AttributeError: 'NoneType' object has no attribute 'value'
WARNING:root:Brightness is not available
Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 527, in on_universalApplyButton_clicked
    currentFX = fxListBox.get_selected_row().value
AttributeError: 'NoneType' object has no attribute 'value'
WARNING:root:Brightness is not available
Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 527, in on_universalApplyButton_clicked
    currentFX = fxListBox.get_selected_row().value
AttributeError: 'NoneType' object has no attribute 'value'
WARNING:root:Brightness is not available
Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 527, in on_universalApplyButton_clicked
    currentFX = fxListBox.get_selected_row().value
AttributeError: 'NoneType' object has no attribute 'value'

---------------------------------------------------------------------------------------------

**Comment by vitacell** [comment]
EDIT: in razerCommander, every time I push "update" button, it adds another DAchroma to devices

**Comment by z3ntu** [comment]
The AUR package isn't up-to-date thanks to @GabMus . EDIT Will be updated very soon according to him.

**Comment by vitacell** [comment]
Hi, thanks for answer.

What package exactly? razercommander-git 1.0.3-10? what do I need for fix all those problems, it seems that here is more than 1 package that fails or unstable.

**Comment by z3ntu** [comment]
razercommander is just a front-end to the driver. The driver consist out of `razer-driver-dkms`, `razer-daemon` and `python-razer`.

**Comment by z3ntu** [comment]
Did updating to 1.1.8 fix the issue?

**Comment by vitacell** [comment]
[vita@Maquinon64 ~]$ pacman -Q | grep "razer"
python-razer 1.1.8-2
razer-daemon 1.1.8-3
razer-driver-dkms 1.1.8-1
razercommander-git 1.0.3-10

I tryed:
https://bbs.archlinux.org/viewtopic.php?id=221419
https://github.com/terrycain/razer-drivers/issues/67#issuecomment-260419314

Still same problems, nothing works. I thinking to remove that stuff at the moment, and installing back "razercfg". Polychromatic doesn't work too. GTK is bugged. What should I do? can you help me?

razercfg works great, but it is not compatible with Orbveawer. :(

**Comment by z3ntu** [comment]
```
ls -lah /sys/bus/hid/drivers/
ls -lah /sys/bus/hid/drivers/razerkbd/
ls -lah /sys/bus/hid/drivers/razerkbd/0*/
```
And what do you mean with
> Polychromatic doesn't work too. GTK is bugged.

? If possible, contact me on Telegram @z3ntu, that way it's easier to help you.

**Comment by vitacell** [comment]
[vita@Maquinon64 ~]$ ls -lah /sys/bus/hid/drivers/
total 0
drwxr-xr-x 5 root root 0 ene 25 16:50 .
drwxr-xr-x 4 root root 0 ene 25 00:16 ..
drwxr-xr-x 2 root root 0 ene 25 00:16 hid-generic
drwxr-xr-x 2 root root 0 ene 25 16:50 konepure
drwxr-xr-x 2 root root 0 ene 25 00:16 razermouse

("razermouse" probably that folder was of razercfg)
--------------------------------------------------------------------
[vita@Maquinon64 ~]$ ls -lah /sys/bus/hid/drivers/razerkbd/
ls: no se puede acceder a '/sys/bus/hid/drivers/razerkbd/': No existe el fichero o el directorio
(Can not to access '/sys/bus/hid/drivers/razerkbd/': file or directory does not exist)

same for: ls -lah /sys/bus/hid/drivers/razerkbd/0*/
----------------------------------------------------------------------

http://imgur.com/a/zpY9Z

----------------------------------------------------------------------

I have telegram but I don't know how to add you, it accepts mobile phone number only

**Comment by terricain** [comment]
sudo modprobe razerkbd

**Comment by z3ntu** [comment]
@vitacell Go to the telegram search field and enter `@z3ntu`.

**Comment by vitacell** [comment]
Seems to be some problem of drivers, because I have no output of 
"sudo modprobe razerkbd".
+
razer-driver-meta AUR package has nothing inside, only folders (I removed it anyway).

**Comment by z3ntu** [comment]
Can be closed now (conversation was on Telegram).
