### ISSUE TITLE
razercommander fails to launch

### ISSUE THREAD

**Issue by greyltc** [openrazer/openrazer#208]
When I launch it with my mouse (Naga HexV2) plugged in:
```
Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 74, in <module>
    refreshDevices()
  File "/usr/share/razercommander/main.py", line 70, in refreshDevices
    initDevices()
  File "/usr/share/razercommander/main.py", line 36, in initDevices
    newdev = device.Device(dev)
  File "/usr/share/razercommander/device.py", line 30, in __init__
    self.device)
  File "/usr/share/razercommander/macro_logic.py", line 73, in make_device
    n_device = MacroDevice(mk_arr, device_uid, device)
  File "/usr/share/razercommander/macro_logic.py", line 14, in __init__
    self.set_all_current_macros()
  File "/usr/share/razercommander/macro_logic.py", line 32, in set_all_current_macros
    key.set_current_macro(self.device)
  File "/usr/share/razercommander/macro_logic.py", line 50, in set_current_macro
    self._set_macro(device, self.macro)
  File "/usr/share/razercommander/macro_logic.py", line 43, in _set_macro
    device.macro.del_macro(self.key)
AttributeError: 'RazerMouse' object has no attribute 'macro'
```

**Comment by memoryleakno1** [comment]
Seems like a same issue as what I have yesterday with my Abyss mouse. I haven't got it to work either. :(. I don't know if this post might be a hind to what happeneds:
http://stackoverflow.com/questions/11685936/python-attributeerror-object-has-no-attribute

**Comment by terricain** [comment]
@memoryleakno1 its a separate issue. This is to do with the python library not the daemon

Yeah my bad, I haven't added the lines to the mouse part of the library that allows interracting with macros, should get that done by end of week

**Comment by terricain** [comment]
Done but not released.

**Comment by z3ntu** [comment]
Keeping this open until the next release 🙂

**Comment by terricain** [comment]
Packages are building in launchpad, will be available soon
