### ISSUE TITLE
razer naga chroma fails maxDPI call

### ISSUE THREAD

**Issue by bcoca** [openrazer/openrazer#404]
So this function returns a trace back when called (found it using polychormatic)
https://github.com/openrazer/openrazer/blob/master/pylib/openrazer/client/devices/mice.py#L22
```
Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 1110, in <module>
    indicator.setup()
  File "/usr/bin/polychromatic-tray-applet", line 191, in setup
    self.rebuild_all_submenus()
  File "/usr/bin/polychromatic-tray-applet", line 207, in rebuild_all_submenus
    self.menu_dpi = self._build_dpi_menu()
  File "/usr/bin/polychromatic-tray-applet", line 771, in _build_dpi_menu
    max_dpi = self.active_device.max_dpi
  File "/usr/lib64/python3.5/site-packages/openrazer/client/devices/mice.py", line 31, in max_dpi
    return int(self._dbus_interfaces['dpi'].maxDPI())
  File "/usr/lib64/python3.5/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib64/python3.5/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: maxDPI is not a valid method of interface razer.device.dpi
```

I've made the following hack, for it to work for me:
```python
        try:
            return int(self._dbus_interfaces['dpi'].maxDPI())
        except:
            return 3000  # this should not be hardcoded
```

I don't know the code well enough, but I was thinking the following is needed:
```python
        self._capabilities['maxdpi'] = self._has_feature('razer.device.dpi', ('maxDPI'))
```
and then change the method to rely on that.

Also, the callers don't correctly handle the `None` value, not sure if this method should change or if I  should try to fix the callers.

**Comment by z3ntu** [comment]
Will be included in the next release. Thanks for the report!
If you're using Ubuntu, you can use the daily ppa or on Arch Linux you can use the -git package until then.
