### ISSUE TITLE
Tartarus chroma not being detected

### ISSUE THREAD

**Issue by omgimdrunk** [openrazer/openrazer#409]
Not sure what happened but my Tart-Chrom just won't hang out with the deamon any longer, and causing crashes.

> `4.806711] input: Razer Razer Tartarus Chroma as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.1/1-6.1.1:1.0/0003:1532:0208.0001/input/input13
> [    4.819006] input: Intel(R) RealSense(TM) Camera S as /devices/pci0000:00/0000:00:14.0/usb2/2-6/2-6.3/2-6.3.1/2-6.3.1:1.0/input/input14
> [    4.864087] hid-generic 0003:1532:0208.0001: input,hidraw0: USB HID v1.11 Keyboard [Razer Razer Tartarus Chroma] on usb-0000:00:14.0-6.1.1/input0
> [    4.864277] input: Razer Razer Tartarus Chroma as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.1/1-6.1.1:1.1/0003:1532:0208.0002/input/input15
> [    4.866584] input: Intel(R) RealSense(TM) Camera S as /devices/pci0000:00/0000:00:14.0/usb2/2-6/2-6.3/2-6.3.1/2-6.3.1:1.2/input/input16
> [    4.924115] hid-generic 0003:1532:0208.0002: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer Tartarus Chroma] on usb-0000:00:14.0-6.1.1/input1
> [    4.924237] input: Razer Razer Tartarus Chroma as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.1/1-6.1.1:1.2/0003:1532:0208.0003/input/input17
> [    4.924317] hid-generic 0003:1532:0208.0003: input,hidraw2: USB HID v1.11 Mouse [Razer Razer Tartarus Chroma] on usb-0000:00:14.0-6.1.1/input2
> [    4.924432] input: Razer USB Dongle for Razer Lancehead as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.2/1-6.1.2:1.0/0003:1532:005A.0004/input/input18
> [    4.924497] hid-generic 0003:1532:005A.0004: input,hidraw3: USB HID v1.11 Mouse [Razer USB Dongle for Razer Lancehead] on usb-0000:00:14.0-6.1.2/input0
> [    4.924661] input: Razer USB Dongle for Razer Lancehead as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.2/1-6.1.2:1.1/0003:1532:005A.0005/input/input19
> [    4.955643] input: Razer Razer Stargazer-Microphone as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.3/1-6.3.2/1-6.3.2:1.3/0003:1532:0E01.0008/input/input20
> [    4.984098] hid-generic 0003:1532:005A.0005: input,hidraw4: USB HID v1.11 Keyboard [Razer USB Dongle for Razer Lancehead] on usb-0000:00:14.0-6.1.2/input1
> [    4.984193] input: Razer USB Dongle for Razer Lancehead as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.2/1-6.1.2:1.2/0003:1532:005A.0006/input/input21
> [    5.007840] input: Corsair Corsair K65 RGB Gaming Keyboard  as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.3/1-6.1.3:1.0/0003:1B1C:1B17.0009/input/input22
> [    5.044171] hid-generic 0003:1532:0E01.0008: input,hiddev0,hidraw5: USB HID v1.11 Device [Razer Razer Stargazer-Microphone] on usb-0000:00:14.0-6.3.2/input3
> [    5.104113] hid-generic 0003:1532:005A.0006: input,hidraw6: USB HID v1.11 Keyboard [Razer USB Dongle for Razer Lancehead] on usb-0000:00:14.0-6.1.2/input2
> [    5.104254] input: Razer Razer Kraken 7.1 Chroma as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.4/1-6.4:1.3/0003:1532:0504.0007/input/input23
> [    5.164094] hid-generic 0003:1B1C:1B17.0009: input,hidraw7: USB HID v1.11 Keyboard [Corsair Corsair K65 RGB Gaming Keyboard ] on usb-0000:00:14.0-6.1.3/input0
> [    5.166174] input: Corsair Corsair K65 RGB Gaming Keyboard  as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.3/1-6.1.3:1.1/0003:1B1C:1B17.000A/input/input24
> [    5.224270] hid-generic 0003:1532:0504.0007: input,hiddev1,hidraw8: USB HID v1.11 Device [Razer Razer Kraken 7.1 Chroma] on usb-0000:00:14.0-6.4/input3
> [    5.284091] hid-generic 0003:1B1C:1B17.000A: input,hiddev2,hidraw9: USB HID v1.11 Keyboard [Corsair Corsair K65 RGB Gaming Keyboard ] on usb-0000:00:14.0-6.1.3/input1
> [    5.284134] usbhid 1-6.1.3:1.2: couldn't find an input interrupt endpoint
> [    5.333125] input: Razer Razer Kraken 7.1 Chroma as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.4/1-6.4:1.3/0003:1532:0504.0007/input/input25
> [    5.392259] razerkraken 0003:1532:0504.0007: input,hiddev1,hidraw8: USB HID v1.11 Device [Razer Razer Kraken 7.1 Chroma] on usb-0000:00:14.0-6.4/input3
> [    5.516036] input: Razer Razer Firefly as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.4/1-6.1.4:1.0/0003:1532:0C00.000B/input/input26
> [    5.516215] hid-generic 0003:1532:0C00.000B: input,hidraw10: USB HID v1.11 Mouse [Razer Razer Firefly] on usb-0000:00:14.0-6.1.4/input0
> [    5.517132] input: Razer Razer Firefly as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.4/1-6.1.4:1.1/0003:1532:0C00.000C/input/input27
> [    5.576151] hid-generic 0003:1532:0C00.000C: input,hidraw11: USB HID v1.11 Keyboard [Razer Razer Firefly] on usb-0000:00:14.0-6.1.4/input1
> [    5.576632] input: Razer Razer Firefly as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.4/1-6.1.4:1.2/0003:1532:0C00.000D/input/input28
> [    5.636142] hid-generic 0003:1532:0C00.000D: input,hidraw12: USB HID v1.11 Keyboard [Razer Razer Firefly] on usb-0000:00:14.0-6.1.4/input2
> [    5.969505] input: Razer Razer Firefly as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.4/1-6.1.4:1.2/0003:1532:0C00.000D/input/input29
> [    6.097064] input: Razer Razer Tartarus Chroma as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.1/1-6.1.1:1.0/0003:1532:0208.0001/input/input30
> [    6.147270] input: Razer Razer Tartarus Chroma as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.1/1-6.1.1:1.2/0003:1532:0208.0003/input/input31
> [    6.224947] input: Razer Razer Tartarus Chroma as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.1/1-6.1.1:1.1/0003:1532:0208.0002/input/input32
> [    6.313512] input: Razer Razer Firefly as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.4/1-6.1.4:1.1/0003:1532:0C00.000C/input/input33
> [    6.373033] input: Razer Razer Firefly as /devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6.1/1-6.1.4/1-6.1.4:1.0/0003:1532:0C00.000B/input/input34
> [    6.432311] razerfirefly 0003:1532:0C00.000D: input,hidraw0: USB HID v1.11 Keyboard [Razer Razer Firefly] on usb-0000:00:14.0-6.1.4/input2
> [    6.492564] razerkbd 0003:1532:0208.0001: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer Tartarus Chroma] on usb-0000:00:14.0-6.1.1/input0
> [    6.552580] razerkbd 0003:1532:0208.0003: input,hidraw2: USB HID v1.11 Mouse [Razer Razer Tartarus Chroma] on usb-0000:00:14.0-6.1.1/input2
> [    6.612490] razerkbd 0003:1532:0208.0002: input,hidraw10: USB HID v1.11 Keyboard [Razer Razer Tartarus Chroma] on usb-0000:00:14.0-6.1.1/input1
> [    6.676098] razerfirefly 0003:1532:0C00.000C: input,hidraw11: USB HID v1.11 Keyboard [Razer Razer Firefly] on usb-0000:00:14.0-6.1.4/input1
> [    6.676142] razerfirefly 0003:1532:0C00.000B: input,hidraw12: USB HID v1.11 Mouse [Razer Razer Firefly] on usb-0000:00:14.0-6.1.4/input0

`

udevadm info -a /sys/bus/hid/devices/0003:1532:* | grep -i "Razer Tartarus" -A 6 -B 25
BLANK

> and when running razercommander:
> `jimmy@strix:~$ razercommander 
> Importing device logic, waiting for daemon
> Device logic loaded, daemon is alive
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/razercommander/__main__.py", line 660, in do_command_line
>     self.do_activate()
>   File "/usr/lib/python3.6/site-packages/razercommander/__main__.py", line 634, in do_activate
>     self.refreshDevices()
>   File "/usr/lib/python3.6/site-packages/razercommander/__main__.py", line 275, in refreshDevices
>     self.initDevices()
>   File "/usr/lib/python3.6/site-packages/razercommander/__main__.py", line 221, in initDevices
>     newdev = device.Device(dev)
>   File "/usr/lib/python3.6/site-packages/razercommander/device.py", line 51, in __init__
>     self.device)
>   File "/usr/lib/python3.6/site-packages/razercommander/macro_logic.py", line 73, in make_device
>     n_device = MacroDevice(mk_arr, device_uid, device)
>   File "/usr/lib/python3.6/site-packages/razercommander/macro_logic.py", line 14, in __init__
>     self.set_all_current_macros()
>   File "/usr/lib/python3.6/site-packages/razercommander/macro_logic.py", line 32, in set_all_current_macros
>     key.set_current_macro(self.device)
>   File "/usr/lib/python3.6/site-packages/razercommander/macro_logic.py", line 50, in set_current_macro
>     self._set_macro(device, self.macro)
>   File "/usr/lib/python3.6/site-packages/razercommander/macro_logic.py", line 43, in _set_macro
>     device.macro.del_macro(self.key)
>   File "/usr/lib/python3/dist-packages/openrazer/client/macro.py", line 66, in del_macro
>     raise ValueError("Key {0} is not in openrazer.keyboard.KEY_MAPPING".format(bind_key))
> ValueError: Key 10 is not in openrazer.keyboard.KEY_MAPPING

`

**Comment by omgimdrunk** [comment]
as an update, it appears the daemon can now see the tartarus, but doesn't see output from the device . . .

> python3 event_reader.py --tartarus /dev/input//by-id/usb-
usb-Intel_R__RealSense_TM__Camera_SR300_Intel_R__RealSense_TM__Camera_SR300_610201001911-event-if00
usb-Intel_R__RealSense_TM__Camera_SR300_Intel_R__RealSense_TM__Camera_SR300_610201001911-event-if02
usb-Razer_Razer_BlackWidow_Tournament_Edition_Chroma-event-kbd
usb-Razer_Razer_BlackWidow_Tournament_Edition_Chroma-if01-event-kbd
usb-Razer_Razer_BlackWidow_Tournament_Edition_Chroma-if02-event-mouse
usb-Razer_Razer_BlackWidow_Tournament_Edition_Chroma-if02-mouse
usb-Razer_Razer_Firefly-event-mouse
usb-Razer_Razer_Firefly-if01-event-kbd
usb-Razer_Razer_Firefly-if02-event-kbd
usb-Razer_Razer_Firefly-mouse
usb-Razer_Razer_Kraken_7.1_Chroma-event-if03
usb-Razer_Razer_Stargazer-Microphone_401637L00500127-event-if03
usb-Razer_Razer_Tartarus_Chroma-event-kbd
usb-Razer_Razer_Tartarus_Chroma-if01-event-kbd
usb-Razer_Razer_Tartarus_Chroma-if02-event-mouse
usb-Razer_Razer_Tartarus_Chroma-if02-mouse
usb-Razer_USB_Dongle_for_Razer_Lancehead-event-mouse
usb-Razer_USB_Dongle_for_Razer_Lancehead-if01-event-kbd
usb-Razer_USB_Dongle_for_Razer_Lancehead-if02-event-kbd
usb-Razer_USB_Dongle_for_Razer_Lancehead-mouse
jimmy@strix:~/Documents/projects/git/openrazer/scripts/misc$ python3 event_reader.py --tartarus /dev/input//by-id/usb-Razer_Razer_Tartarus_Chroma-event-kbd 
Starting. Press keys
> 

And pressing the keys on the device does nothing . . . Any thoughts?
