### ISSUE TITLE
Constant exception in razer_daemon/misc/screensaver_thread.py

### ISSUE THREAD

**Issue by volvofixthis** [openrazer/openrazer#41]
```
2016-09-09 20:48:05 | razer.screensaver              | INFO     | Initialising DBus screensaver object
2016-09-09 20:48:05 | razer.screensaver              | ERROR    | Caught exception in run loop
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/razer_daemon/misc/screensaver_thread.py", line 122, in run
    screensaver_active = self._dbus_interface.GetActive()
  File "/usr/lib64/python3.4/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownObject: No such object path '/org/gnome/ScreenSaver'
2016-09-09 20:48:05 | razer.screensaver              | INFO     | Initialising DBus screensaver object
2016-09-09 20:48:05 | razer.screensaver              | ERROR    | Caught exception in run loop
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/razer_daemon/misc/screensaver_thread.py", line 122, in run
    screensaver_active = self._dbus_interface.GetActive()
  File "/usr/lib64/python3.4/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownObject: No such object path '/org/gnome/ScreenSaver'
```

Maybe this patch is ok:

```
--- daemon/razer_daemon/misc/screensaver_thread.py  2016-09-09 20:38:11.630578319 +0300
+++ /usr/lib64/python3.4/site-packages/razer_daemon/misc/screensaver_thread.py  2016-09-09 20:55:07.459549739 +0300
@@ -136,7 +136,9 @@
                 except Exception as err:
                     self.logger.exception("Caught exception in run loop", exc_info=err)
                     self._dbus_interface = None
-
+                    self._try_count += 1
+            else:
+                break

             # Sleep
             time.sleep(0.1)
```

**Comment by terricain** [comment]
Nah as if it breaks the screensaver thread stops before it should, other things need to be fixed for that to happen. 

Haved _fixed_ this on my copy will push later.
