### ISSUE TITLE
Razer Core driverless support

### ISSUE THREAD

**Issue by lezed1** [openrazer/openrazer#473]
I'm on Arch and just installed the [AUR package](https://aur.archlinux.org/packages/openrazer-meta-git/) (modified to use the hid branch). After `chown`ing and `chmod`ing `/dev/hidraw*`, I ran the daemon. I got this (shortened) error:

```
zander@amperZand: ~
$ openrazer-daemon -rF                                                                                                       [19:26:47]
No pidfile found, assuming openrazer-daemon is not running
Starting daemon.
2017-12-10 19:31:16 | razer                          | INFO     | Initialising Daemon (v2.1.1). Pid: 11869
2017-12-10 19:31:16 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2017-12-10 19:31:16 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
### EDITED OUT TO SHORTEN
2017-12-10 19:31:16 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/daemonize.py", line 245, in start
    self.action(*privileged_action_result)
  File "/usr/bin/openrazer-daemon", line 132, in run_daemon
    bustype=bustype)
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/daemon.py", line 117, in __init__
    self._load_devices(first_run=True)
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/daemon.py", line 393, in _load_devices
    if device_class.match(sys_name, sys_path):  # Check it matches sys/ ID format and is supported
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 806, in match
    hidraw_path = os.path.join('/dev', os.listdir(os.path.join(dev_path, 'hidraw'))[0])
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:01.0/0000:05:00.0/0000:06:04.0/0000:08:00.0/usb3/3-1/3-1.2/3-1.2:1.0/0003:1532:0215.0002/hidraw'
```

The folder `/sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:01.0/0000:05:00.0/0000:06:04.0/0000:08:00.0/usb3/3-1/3-1.2/3-1.2:1.0/0003:1532:0215.0002/` exists, but doesn't have a file called `hidraw` in it.

**Comment by lezed1** [comment]
I've tried rebooting and replugging the Core, this time the daemon failed on a Firefly:

```
Starting daemon.
2017-12-12 05:32:44 | razer                          | INFO     | Initialising Daemon (v2.1.1). Pid: 14477
########### REMOVED TO SHORTEN
2017-12-12 05:32:45 | razer                          | INFO     | Found device.0: 0003:1532:0C00.0007
2017-12-12 05:32:45 | razer.device0                  | INFO     | Initialising device.0 RazerFirefly
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/daemonize.py", line 245, in start
    self.action(*privileged_action_result)
  File "/usr/bin/openrazer-daemon", line 132, in run_daemon
    bustype=bustype)
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/daemon.py", line 117, in __init__
    self._load_devices(first_run=True)
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/daemon.py", line 415, in _load_devices
    razer_device = device_class(sys_path, device_number, self._config, testing=self._test_dir is not None, additional_interfaces=sorted(additional_interfaces))
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 192, in __init__
    self.serial = self.get_serial()
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 391, in get_serial
    serial = self.get_hidraw_serial()
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 378, in get_hidraw_serial
    response = self.razer_send_payload(request)
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 284, in razer_send_payload
    response_report = self.razer_get_usb_response(request_report)
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 263, in razer_get_usb_response
    self.hid_node.sendFeatureReport(data.bytes, report_num=self.hid_request_index)
  File "/usr/lib/python3.6/site-packages/hidraw/__init__.py", line 111, in sendFeatureReport
    buf = ctypes.create_string_buffer(chr(report_num) + report, length)
TypeError: must be str, not bytearray

Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 825, in __del__
    self.close()
  File "/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/device_base.py", line 720, in close
    if not self._is_closed:
AttributeError: 'RazerFirefly' object has no attribute '_is_closed'
Stopping daemon.
```

Removing the Firefly and rerunning the daemon leads to no devices recognized.
