### ISSUE TITLE
Daemon is not responding Fedora 27

### ISSUE THREAD

**Issue by kentgr** [openrazer/openrazer#554]
I got a problem since a few weeks back that the daemon is not responding and read the case https://github.com/openrazer/openrazer/issues/461 but it does not help. 

This is the error i get: 
```
python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/openrazer/client/__init__.py", line 38, in __init__
    device = _RazerDeviceFactory.get_device(serial)
  File "/usr/lib/python3.6/site-packages/openrazer/client/device.py", line 51, in get_device
    device_type = device_dbus.getDeviceType()
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getDeviceType is not a valid method of interface razer.device.misc
```

**Comment by z3ntu** [comment]
What does `pkill -e -f openrazer-daemon; openrazer-daemon -Fv` output?

**Comment by kentgr** [comment]
```
pkill -e -f openrazer-daemon; openrazer-daemon -Fv 
Starting daemon.
2018-03-23 16:28:03 | razer                          | INFO     | Initialising Daemon (v2.2.2). Pid: 10088
2018-03-23 16:28:03 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus1800 ------------------------ (1532:0020)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusV2 -------------------------- (1532:005B)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassic ------------------ (1532:011B)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassicAlternate --------- (1532:010E)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2012 ------------- (1532:010D)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2013 ------------- (1532:011A)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2016 ------------- (1532:0214)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXTournamentEditionChroma - (1532:021A)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017 ----------------------- (1532:0225)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017FullHD ----------------- (1532:022F)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2017 --------------- (1532:0232)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthMid2017 ---------------- (1532:022D)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderChroma ------------------- (1532:0043)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderElite -------------------- (1532:005C)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerExpert ----------------- (1532:0202)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerFirefly ---------------------------- (1532:0C00)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerImperator -------------------------- (1532:002F)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerKrakenClassic ---------------------- (1532:0501)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerMambaTE ---------------------------- (1532:0046)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerNagaChroma ------------------------- (1532:0053)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
2018-03-23 16:28:03 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
2018-03-23 16:28:03 | razer                          | INFO     | Found device.0: 0003:1532:0C00.0004
2018-03-23 16:28:03 | razer.device0                  | INFO     | Initialising device.0 RazerFirefly
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.brightness.getBrightness method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.brightness.setBrightness method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setWave method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setStatic method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setSpectrum method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setReactive method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setNone method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathRandom method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathSingle method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathDual method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setCustom method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setKeyRow method to DBus
2018-03-23 16:28:04 | razer.device0                  | DEBUG    | Adding razer.device.misc.triggerReactive method to DBus
2018-03-23 16:28:04 | razer                          | INFO     | Found device.1: 0003:1532:0041.0001
2018-03-23 16:28:04 | razer.device1                  | INFO     | Initialising device.1 RazerNagaHex
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.dpi.maxDPI method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.dpi.getDPI method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.dpi.setDPI method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.getPollRate method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.misc.setPollRate method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.lighting.logo.getLogoActive method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.lighting.logo.setLogoActive method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.lighting.scroll.getScrollActive method to DBus
2018-03-23 16:28:04 | razer.device1                  | DEBUG    | Adding razer.device.lighting.scroll.setScrollActive method to DBus
2018-03-23 16:28:04 | razer                          | INFO     | Found device.2: 0003:1532:0111.0005
2018-03-23 16:28:04 | razer.device2                  | INFO     | Initialising device.2 RazerNostromo
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.brightness.getBrightness method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.brightness.setBrightness method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.brightness.getBrightness method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.brightness.setBrightness method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.profile_led.getRedLED method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.profile_led.setRedLED method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.profile_led.getGreenLED method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.profile_led.setGreenLED method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.profile_led.getBlueLED method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.lighting.profile_led.setBlueLED method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.macro.getMacros method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.macro.deleteMacro method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.macro.addMacro method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.macro.getModeModifier method to DBus
2018-03-23 16:28:04 | razer.device2                  | DEBUG    | Adding razer.device.macro.setModeModifier method to DBus
2018-03-23 16:28:04 | razer.device2.keymanager       | DEBUG    | Starting KeyWatcher
2018-03-23 16:28:04 | razer                          | INFO     | Found device.3: 0003:1532:0216.000E
2018-03-23 16:28:04 | razer.device3                  | INFO     | Initialising device.3 RazerBlackWidowXChroma
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.brightness.getBrightness method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.brightness.setBrightness method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.brightness.getBrightness method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.brightness.setBrightness method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.brightness.getBrightness method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.brightness.setBrightness method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setWave method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setStatic method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setSpectrum method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setReactive method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setNone method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathRandom method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathSingle method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathDual method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setCustom method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.chroma.setKeyRow method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.led.gamemode.getGameMode method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.led.gamemode.setGameMode method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.led.macromode.getMacroMode method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.led.macromode.setMacroMode method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.led.macromode.getMacroEffect method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.led.macromode.setMacroEffect method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.macro.getMacros method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.macro.deleteMacro method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.macro.addMacro method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.custom.setRipple method to DBus
2018-03-23 16:28:04 | razer.device3                  | DEBUG    | Adding razer.device.lighting.custom.setRippleRandomColour method to DBus
2018-03-23 16:28:04 | razer.device3.keymanager       | DEBUG    | Starting KeyWatcher
2018-03-23 16:28:04 | razer.device3                  | INFO     | Putting device into driver mode. Daemon will handle special functionality
2018-03-23 16:28:04 | razer                          | DEBUG    | Adding razer.devices.syncEffects method to DBus
2018-03-23 16:28:04 | razer                          | DEBUG    | Adding razer.devices.enableTurnOffOnScreensaver method to DBus
2018-03-23 16:28:04 | razer                          | DEBUG    | Adding razer.devices.getDevices method to DBus
2018-03-23 16:28:04 | razer                          | DEBUG    | Adding razer.devices.getOffOnScreensaver method to DBus
2018-03-23 16:28:04 | razer                          | DEBUG    | Adding razer.devices.supportedDevices method to DBus
2018-03-23 16:28:04 | razer                          | DEBUG    | Adding razer.daemon.version method to DBus
2018-03-23 16:28:04 | razer                          | DEBUG    | Adding razer.daemon.stop method to DBus
2018-03-23 16:28:04 | razer                          | DEBUG    | Adding razer.devices.getSyncEffects method to DBus
2018-03-23 16:28:04 | razer                          | INFO     | Serving DBus
^C2018-03-23 16:28:31 | razer                          | INFO     | Stopping daemon on signal 2
2018-03-23 16:28:31 | razer.device2.keymanager       | DEBUG    | Stopping key manager
2018-03-23 16:28:31 | razer.device3.keymanager       | DEBUG    | Stopping key manager
2018-03-23 16:28:31 | razer.device3.ripplemanager    | DEBUG    | Closing Ripple Manager
^CStopping daemon.
```

**Comment by z3ntu** [comment]
You can apply the diff of f5c4fe6 manually to the file `/usr/lib/python3.6/site-packages/openrazer_daemon/hardware/keyboards.py` or wait for the next release (which might take some time though).
