### ISSUE TITLE
Support for Clear Linux

### ISSUE THREAD

**Issue by xacrimon** [openrazer/openrazer#837]
### Distro

Clear Linux

### Issue

Hello! I'd like you awesome folks to consider adding support for Clear Linux. https://clearlinux.org/

**Comment by z3ntu** [comment]
I've followed the [guide on the Clear Linux homepage](https://clearlinux.org/documentation/clear-linux/guides/maintenance/autospec#example-2-build-a-new-rpm) but that tools crashes for me and nobody has helped me from IRC #clearlinux yet.

```
root@clr-23645250d51d4d6aac72f611a947c647 ~/clearlinux/packages/openrazer # make autospec
Remote not yet initialized. Continuing.
rm -rf ./rpms
rm -f ./results/*.rpm
rm -f ./results/*.log
python3 ../../projects/autospec/autospec/autospec.py \
        --target . \
        --integrity \
        --config "../../projects/common/conf/autospec.conf" \
        --name openrazer \
        --archives  \
        --mock-config /root/clearlinux/projects/common/conf/clear.cfg \
        --mock-opts "" \
        ${SETVERSION:+ --version ${SETVERSION}} \
           \
        https://github.com/openrazer/openrazer/archive/v2.5.0.tar.gz;
ARCHIVES []


Processing https://github.com/openrazer/openrazer/archive/v2.5.0.tar.gz
=========================================================================================================
Name        : openrazer
Version     : 2.5.0
Prefix      : openrazer-2.5.0
Warning: Set [autospec][packages_file] path to package list file for requires validation
Warning: Set [autospec][git] upstream template for remote git URI configuration
Warning: Set [autospec][license_fetch] uri for license fetch support
Warning: Set [autospec][license_show] uri for license link check support
Warning: Set [autospec][yum_conf] path to yum.conf file for whatrequires validation
Buildreqs   : buildreq-cmake buildreq-distutils3 
Summary     : No detailed summary available
Licenses    :  LICENSE


-------------------------------------------------------------------------------
Performing package integrity verification

INFO   : None of v2.5.0.tar.gz.(asc|sig|sign|sha256) is found in .
Building package openrazer round 1
openrazer mock chroot at /var/lib/mock/clear-openrazer
Traceback (most recent call last):
  File "../../projects/autospec/autospec/autospec.py", line 362, in <module>
    main()
  File "../../projects/autospec/autospec/autospec.py", line 237, in main
    package(args, url, name, archives, workingdir, infile_dict)
  File "../../projects/autospec/autospec/autospec.py", line 307, in package
    build.package(filemanager, args.mock_config, args.mock_opts, args.cleanup)
  File "/root/clearlinux/projects/autospec/autospec/build.py", line 314, in package
    logfile="%s/results/mock_srpm.log" % download_path, cwd=download_path)
  File "/root/clearlinux/projects/autospec/autospec/util.py", line 47, in call
    raise subprocess.CalledProcessError(returncode, full_args["args"], None)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/mock', '-r', '/root/clearlinux/projects/common/conf/clear.cfg', '--buildsrpm', '--sources=./', '--spec=openrazer.spec', '--uniqueext=openrazer', '--result=results/', '--no-cleanup-after']' returned non-zero exit status 4.
make: *** [../common/Makefile.common:168: autospec] Error 1
```

```
root@clr-23645250d51d4d6aac72f611a947c647 ~/clearlinux/packages/openrazer # cat results/mock_srpm.log 
INFO: mock.py version 1.2.14 starting (python version = 3.7.3)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
INFO: Start(openrazer.spec)  Config(clear)
Start: clean chroot
Finish: clean chroot
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
Mock Version: 1.2.14
INFO: Mock Version: 1.2.14
WARNING: File /etc/hosts not present. It is not copied into the chroot.
WARNING: File /etc/localtime not present. It is not copied into the chroot.
Start: dnf install
Finish: dnf install
ERROR: Exception(openrazer.spec) Config(clear) 0 minutes 15 seconds
INFO: Results and/or logs in: results/
ERROR: Command failed. See logs for output.
 # /usr/sbin/useradd -m -u 0 -g 302 -d /builddir  mockbuild
```

Nothing helpful in the logs unfortunately.
