### ISSUE TITLE
KDE Neon Support

### ISSUE THREAD

**Issue by MuhammetDilmac** [openrazer/openrazer#898]
Hello guys,
I try to add ppa for KDE Neon but not succeed. Can KDE Neon support be added?

```shell script
$ lsb_release -a
Distributor ID: neon
Description:    KDE neon User Edition 5.16
Release:        18.04
Codename:       bionic
```

**Comment by z3ntu** [comment]
Hi, can you send me the error message you got? It should generally work with the PPA as KDE Neon is based on Ubuntu.

**Comment by MuhammetDilmac** [comment]
When i try to add ppa;
```shell
$ sudo add-apt-repository ppa:openrazer/stable
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 107, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 117, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 612, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for neon/bionic
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Böyle bir dosya ya da dizin yok: '/var/crash/_usr_bin_add-apt-repository.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 107, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 117, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 612, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for neon/bionic
```

**Comment by z3ntu** [comment]
It looks like a [bug for this issue](https://phabricator.kde.org/T9294) was closed on July 31st 2018, so I'm not sure why you're hitting that issue. But anyways, you should be able to get help in KDE Neon support channels, as this is definitely an issue on their side. I'm closing this issue but if you need anything else, feel free to comment.
